apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: node:alpine
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: app-volume
          mountPath: /usr/src/app
        command: ["node", "server.js"]
      volumes:
      - name: app-volume
        hostPath:
          path: /home/gabriel/Documentos/docker/devopsT1/backend

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

